---
- name: Copying the vaul-pass file and Static Analysis folder to directory /home/vagrant/
  hosts: localhost
  
  tasks:
  - name: Check if .vault-pass file is present
    local_action: stat path='/bakerx/.vault-pass'
    register: check

  - name: Copy the .vault-pass file to the home directory of VM.
    copy:
      src: '/bakerx/.vault-pass'
      dest: '~/.vault-pass'
      mode: 0644
    when: check.stat.exists
    
  - name: Copy the Static Analysis folder to config-srv
    copy:
      src: '/bakerx/Static_Analysis'
      dest: '~'
      mode: 777
  
  - name: Setting permissions
    shell: chmod -R 777 /home/vagrant/Static_Analysis/
    become: yes

