---
- name: Install Dependencies
  hosts: localhost

  vars_files: 
    - ../vars/vars.yml

  tasks:
  - name: Installing Nodejs
    apt: pkg='nodejs' state='present'
    become: yes

  - name: Install NPM
    apt: pkg='npm' state='present'
    become: yes

  - name: Install Java.
    apt: pkg="openjdk-11-jdk" state='present'
    become: yes


