---
- name: Install Jenkins Plugin
  hosts: localhost
  
  vars_files: 
    - ../vars/vars.yml

  vars:
    - username: "{{jenkins_username}}"
    - password: "{{jenkins_password}}"
    
  tasks:
  - name: Install Jenkins
    shell: "wget -q -O - https://pkg.jenkins.io/debian-stable/jenkins.io.key | sudo apt-key add -"
    become: yes

  - name: Downloading Jenkins Package
    shell: "sudo sh -c 'echo deb https://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'"
    become: yes

  - name: Apt update.
    shell: "sudo apt-get update"
    become: yes

  - name: Install Jenkins.
    shell: "sudo apt-get install jenkins -y"
    become: yes

  - name: Changing the port from 8080 to 9000
    shell: "sudo sed -i 's/8080/9000/' /etc/default/jenkins"

  - name: Restart Jenkins
    service:
      name: jenkins
      state: restarted
    become: yes

  - name: Wait for the jenkin services to come up.
    wait_for:
      port: 9000
      delay: 40

  - name: Create a file directory init.groovy.d
    file:
      path: /var/lib/jenkins/init.groovy.d
      state: directory
    become: yes

  - name: Creating a file with name basic-security.groovy
    template:
      src: JinjaTemplates/groovy.j2
      dest: /var/lib/jenkins/init.groovy.d/basic-security.groovy
    become: yes

  - name: Restarting the Jenkins service
    service:
      name: jenkins
      state: restarted
    become: yes

  - name: Waiting for the service jenkins to come up on port 9000
    wait_for:
      port: 9000
      delay: 80

  - name: Install Jenkins Plugins
    jenkins_plugin:
      name: "{{ item }}"
      url_username: "{{jenkins_username}}"
      url_password: "{{jenkins_password}}"
      url: "{{jenkins_url}}"
    retries: 2
    with_items:
      - junit
      - pipeline-model-definition
      - bootstrap4-api
      - pipeline-model-api
      - jquery3-api
      - postbuild-task
      - workflow-basic-steps
      - postbuildscript
      - token-macro
      - plain-credentials
      - trilead-api
      - checks-api
      - git-server
      - pipeline-rest-api
      - build-timeout
      - script-security
      - momentjs
      - git-client
      - echarts-api
      - cloudbees-folder
      - resource-disposer
      - credentials-binding
      - ssh-credentials
      - workflow-aggregator
      - pipeline-milestone-step
      - branch-api
      - popper-api
      - workflow-job
      - pipeline-stage-tags-metadata
      - lockable-resources
      - jaxb
      - pipeline-graph-analysis
      - workflow-api
      - pipeline-model-extensions
      - ws-cleanup
      - workflow-step-api
      - structs
      - workflow-durable-task-step
      - plugin-util-api
      - display-url-api
      - apache-httpcomponents-client-4-api
      - snakeyaml-api
      - test-stability
      - git
      - workflow-scm-step
      - jackson2-api
      - ace-editor
      - mailer
      - workflow-support
      - command-launcher
      - durable-task
      - handlebars
      - pipeline-build-step
      - matrix-project
      - pipeline-stage-step
      - jdk-tool
      - pipeline-input-step
      - credentials
      - font-awesome-api
      - jsch
      - workflow-cps-global-lib
      - workflow-cps
      - scm-api
      - workflow-multibranch
      - bouncycastle-api
      - antisamy-markup-formatter
      - timestamper
      - ant
      - gradle
      - jjwt-api
      - okhttp-api
      - github-api
      - github
      - github-branch-source
      - pipeline-github-lib
      - ssh-slaves
      - matrix-auth
      - pam-auth
      - ldap
      - email-ext
      - sshd
      - pipeline-stage-view

  - name: Restarting the Jenkins service
    service:
      name: jenkins
      state: restarted
    become: yes

  - name: Waiting for the service jenkins to come up on port 9000
    wait_for:
      port: 9000
      delay: 80

