---
- name: Download and Configure Jenkins CLI
  hosts: localhost
  vars_files:
    - ../vars/vars.yml

  tasks:

  - name: Install job builder python package
    apt:
      name: jenkins-job-builder
      state: present
    become: yes

  - name: Install jmespath
    pip:
      name: jmespath
      state: present
    become: yes

  - name: Jenkins CLI Download
    get_url:
      url: "{{jenkins_url}}/jnlpJars/jenkins-cli.jar"
      dest: "~/"
      mode: 0755
    become: yes


