---
- name: Updating the inventory file
  hosts: localhost
  vars:
    itrust_ip: "{{ itrust_ip }}"
    checkbox_ip: "{{ checkbox_ip }}"
    monitoring_ip: "{{ monitoring_ip }}"

  tasks:
  - name: Delete inventory file if it already exists.
    file:
      path: /bakerx/cm/Ansible_Scripts/inventory.ini
      state: absent
    become: yes

  - name: Creating inventory.ini file
    file:
      path: /bakerx/cm/Ansible_Scripts/inventory.ini
      state: touch
    become: yes

  - name: Adding the iTrust IP to the inventory file
    lineinfile:
      state: present
      insertafter: EOF
      dest: /bakerx/cm/Ansible_Scripts/inventory.ini
      line: "{{ item }}"
    with_items:
      - '[itrust]'
      - '{{ itrust_ip }} ansible_user=root'

  - name: Adding the checkbox_ip to the inventory file
    lineinfile:
      state: present
      insertafter: EOF
      dest: /bakerx/cm/Ansible_Scripts/inventory.ini
      line: "{{ item }}"
    with_items:
      - '[checkbox]'
      - '{{ checkbox_ip }} ansible_user=root'
  
  - name: Adding the monitoring_ip to the inventory file
    lineinfile:
      state: present
      insertafter: EOF
      dest: /bakerx/cm/Ansible_Scripts/inventory.ini
      line: "{{ item }}"
    with_items:
      - '[monitor]'
      - '{{ monitoring_ip }} ansible_user=root'