---
- name: Update apt repo and cache on all Debian/Ubuntu boxes.
  become: yes
  apt: 
    update_cache: yes 
    force_apt_get: yes 
    cache_valid_time: 3600

- name: Install nodejs package. 
  become: yes
  apt:
    state: present
    name: nodejs

- name: Install npm package. 
  become: yes
  apt:
    state: present
    name: npm