---
- name: Updating the inventory file for the canary analysis
  hosts: localhost
  vars:
    blue_server_ip: "{{ blue_server_ip }}"
    green_server_ip: "{{ green_server_ip }}"
    proxy_server_ip: "{{ proxy_server_ip }}"
  
  tasks:
  - name: Delete canary inventory file if it already exists.
    file:
      path: /bakerx/cm/canary_inventory.ini
      state: absent
    become: yes

  - name: Creating canary_inventory.ini file
    file:
      path: /bakerx/cm/canary_inventory.ini
      state: touch
    become: yes
  
  - name: change permissions
    file:
      path: ~/.ssh/deploy_rsa
      state: file
      owner: vagrant
      group: vagrant
      mode: "400"

  - name: Adding the Blue server IP to the inventory file
    lineinfile:
      state: present
      insertafter: EOF
      dest: /bakerx/cm/canary_inventory.ini
      line: "{{ item }}"
    with_items:
      - '[blue_server]'
      - "{{ blue_server_ip }} ansible_ssh_private_key_file=~/.ssh/deploy_rsa ansible_ssh_common_args='-o StrictHostKeyChecking=no' ansible_ssh_user=vagrant"
      #- '[blue_server:vars]'
      # - "ansible_ssh_common_args='-o StrictHostKeyChecking=no'"

  - name: Adding the Green Server IP to the inventory file
    lineinfile:
      state: present
      insertafter: EOF
      dest: /bakerx/cm/canary_inventory.ini
      line: "{{ item }}"
    with_items:
      - '[green_server]'
      - "{{ green_server_ip }} ansible_ssh_private_key_file=~/.ssh/deploy_rsa ansible_ssh_common_args='-o StrictHostKeyChecking=no' ansible_ssh_user=vagrant"
      # - '[green_server:vars]'
      # - "ansible_ssh_common_args='-o StrictHostKeyChecking=no'"
  
  - name: Adding the monitoring_ip to the inventory file
    lineinfile:
      state: present
      insertafter: EOF
      dest: /bakerx/cm/canary_inventory.ini
      line: "{{ item }}"
    with_items:
      - '[proxy_server]'
      - "{{ proxy_server_ip }} ansible_ssh_private_key_file=~/.ssh/deploy_rsa ansible_ssh_common_args='-o StrictHostKeyChecking=no' ansible_ssh_user=vagrant"
      # - '[proxy_server:vars]'
      # - "ansible_ssh_common_args='-o StrictHostKeyChecking=no'"