---
- name: ITrust Mutation
  hosts: localhost
  vars_files:
    - vars/vars.yml
  
  tasks:
    - name: Git clone ITrust Directory to /home/vargrant
      shell: git clone https://{{ git_uname }}:{{ git_passwd }}@github.ncsu.edu/engr-csc326-staff/iTrust2-v8.git /home/vagrant/iTrust
    
    - name: Modifying the pom.xml file.
      copy:
        src: /bakerx/cm/Ansible_Scripts/JinjaTemplates/pom.xml
        dest: /home/vagrant/iTrust/iTrust2/pom.xml
        mode: 777

    - name: Copy application.yml template.
      copy:
        src: /home/vagrant/iTrust/iTrust2/src/main/resources/application.yml.template
        dest: /home/vagrant/iTrust/iTrust2/src/main/resources/application.yml
        mode: 777
    
    - name: Add the password to the application.yml file
      shell: "sed -i 's/    password:/    password: root/g' /home/vagrant/iTrust/iTrust2/src/main/resources/application.yml"

    - name: Copy Fuzzing directory to /home/vagrant/
      shell: '(cd /bakerx/ && cp -r Fuzzing /home/vagrant/)'

    - name: Run Fuzzing 
      shell: '(cd /home/vagrant/Fuzzing/ && npm install && node index.js {{check}})'
      register: log    
      
    - name: Show log
      debug:
        msg: "{{ log.stdout_lines }}"