
---
- name: Specify MySQL root password before installing MySQL
  become: yes
  debconf:
    name: mysql-server
    question: mysql-server/root_password
    value: '{{ mysql_root_pass }}'
    vtype: password

- name: MySQL root password confirmation
  become: yes
  debconf:
    name: mysql-server
    question: mysql-server/root_password_again
    value: '{{ mysql_root_pass }}'
    vtype: password

- name: Installing MySQL.
  become: yes
  apt: 
    name: mysql-server
    state: present
  
# - name: Update MySQL root password.
#   mysql_user:
#     name: root
#     password: "{{ mysql_root_pass }}"
#     state: present
#   become: yes

- name: Install pip, setuptools
  become: yes
  apt:
    name: ['python3-pip', 'python-setuptools']
    state: present
    update_cache: yes

- name: Package Upgrade
  apt:
    name: "*"
    state: latest
  become: yes
    
- name: Restarting the MySQL Server
  become: yes
  service:
    name: mysql
    state: restarted
    enabled: true

# Reference For changing the password for root - https://stackoverflow.com/questions/42267299/ansible-install-mysql-5-7-set-root-user-password


  