---
- name: Wait for system to become reachable
  wait_for_connection:
    timeout: 120
    
- name: Install nginx
  become: true
  apt:
    name: nginx
    state: latest

- name: Start nginx service
  service:
    name: nginx
    state: started
