---
- name: Add the git credentials environment variables
  become: yes
  blockinfile:
    path: /etc/environment
    block: |
      GIT_USERNAME={{ git_uname }}
      GIT_PASSWORD={{ git_passwd }}
    state: present
