---
- name: Add the git and mysql credentials environment variables
  become: yes
  blockinfile:
    path: /etc/environment
    block: |
      GIT_USERNAME={{ git_uname }}
      GIT_PASSWORD={{ git_passwd }}
      DB_PASS={{ mysql_root_pass }}
    state: present
