---
- name: Wait for system to become reachable
  wait_for_connection:
    timeout: 120
    
- name: npm install
  command: npm install
  args:
    chdir: /bakerx/Monitoring/agent/

- name: pm2 start index.js
  command: pm2 start index.js
  args:
    chdir: /bakerx/Monitoring/agent/
