
---
- name: Update apt repo and cache on all Debian/Ubuntu boxes
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  become: yes

- name: Upgrade all packages on servers
  apt: upgrade=dist force_apt_get=yes
  become: yes

- name: Install Java.
  apt: pkg="openjdk-11-jdk" state='present'
  become: yes

- name: Install Python
  apt: pkg="python3" state='present'
  become: yes
